/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickingIdRouteImport } from './routes/picking.$id'
import { Route as OpsVentasRouteImport } from './routes/ops.ventas'
import { Route as OpsTraspasosRouteImport } from './routes/ops.traspasos'
import { Route as OpsRecibosRouteImport } from './routes/ops.recibos'
import { Route as OpsProductosRouteImport } from './routes/ops.productos'
import { Route as OpsOrdenesTrabajoRouteImport } from './routes/ops.ordenes-trabajo'
import { Route as OpsInventarioRouteImport } from './routes/ops.inventario'
import { Route as OpsHerramientasRouteImport } from './routes/ops.herramientas'
import { Route as OpsGarantiasRouteImport } from './routes/ops.garantias'
import { Route as OpsEnsamblesRouteImport } from './routes/ops.ensambles'
import { Route as OpsDevolucionesRouteImport } from './routes/ops.devoluciones'
import { Route as OpsCotizacionesRouteImport } from './routes/ops.cotizaciones'
import { Route as OpsComprasRouteImport } from './routes/ops.compras'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTop10RouteImport } from './routes/admin.top-10'
import { Route as AdminReordenRouteImport } from './routes/admin.reorden'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConteoCiclicoRouteImport } from './routes/admin.conteo-ciclico'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminCierresRouteImport } from './routes/admin.cierres'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAnalisisAbcRouteImport } from './routes/admin.analisis-abc'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'
import { Route as OpsVentasIndexRouteImport } from './routes/ops.ventas.index'
import { Route as OpsRecibosIndexRouteImport } from './routes/ops.recibos.index'
import { Route as OpsOrdenesTrabajoIndexRouteImport } from './routes/ops.ordenes-trabajo.index'
import { Route as OpsGarantiasIndexRouteImport } from './routes/ops.garantias.index'
import { Route as OpsDevolucionesIndexRouteImport } from './routes/ops.devoluciones.index'
import { Route as OpsCotizacionesIndexRouteImport } from './routes/ops.cotizaciones.index'
import { Route as OpsVentasNuevaRouteImport } from './routes/ops.ventas.nueva'
import { Route as OpsVentasIdRouteImport } from './routes/ops.ventas.$id'
import { Route as OpsRecibosNuevaRouteImport } from './routes/ops.recibos.nueva'
import { Route as OpsRecibosIdRouteImport } from './routes/ops.recibos.$id'
import { Route as OpsOrdenesTrabajoIdRouteImport } from './routes/ops.ordenes-trabajo.$id'
import { Route as OpsGarantiasNuevaRouteImport } from './routes/ops.garantias.nueva'
import { Route as OpsGarantiasIdRouteImport } from './routes/ops.garantias.$id'
import { Route as OpsDevolucionesNuevaRouteImport } from './routes/ops.devoluciones.nueva'
import { Route as OpsDevolucionesIdRouteImport } from './routes/ops.devoluciones.$id'
import { Route as OpsCotizacionesNuevaRouteImport } from './routes/ops.cotizaciones.nueva'
import { Route as OpsCotizacionesIdRouteImport } from './routes/ops.cotizaciones.$id'

const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingIdRoute = PickingIdRouteImport.update({
  id: '/picking/$id',
  path: '/picking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsVentasRoute = OpsVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => OpsRoute,
} as any)
const OpsTraspasosRoute = OpsTraspasosRouteImport.update({
  id: '/traspasos',
  path: '/traspasos',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRecibosRoute = OpsRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => OpsRoute,
} as any)
const OpsProductosRoute = OpsProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => OpsRoute,
} as any)
const OpsOrdenesTrabajoRoute = OpsOrdenesTrabajoRouteImport.update({
  id: '/ordenes-trabajo',
  path: '/ordenes-trabajo',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventarioRoute = OpsInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => OpsRoute,
} as any)
const OpsHerramientasRoute = OpsHerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => OpsRoute,
} as any)
const OpsGarantiasRoute = OpsGarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEnsamblesRoute = OpsEnsamblesRouteImport.update({
  id: '/ensambles',
  path: '/ensambles',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDevolucionesRoute = OpsDevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCotizacionesRoute = OpsCotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComprasRoute = OpsComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => OpsRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTop10Route = AdminTop10RouteImport.update({
  id: '/top-10',
  path: '/top-10',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReordenRoute = AdminReordenRouteImport.update({
  id: '/reorden',
  path: '/reorden',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteoCiclicoRoute = AdminConteoCiclicoRouteImport.update({
  id: '/conteo-ciclico',
  path: '/conteo-ciclico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCierresRoute = AdminCierresRouteImport.update({
  id: '/cierres',
  path: '/cierres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalisisAbcRoute = AdminAnalisisAbcRouteImport.update({
  id: '/analisis-abc',
  path: '/analisis-abc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)
const OpsVentasIndexRoute = OpsVentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsVentasRoute,
} as any)
const OpsRecibosIndexRoute = OpsRecibosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRecibosRoute,
} as any)
const OpsOrdenesTrabajoIndexRoute = OpsOrdenesTrabajoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsOrdenesTrabajoRoute,
} as any)
const OpsGarantiasIndexRoute = OpsGarantiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsGarantiasRoute,
} as any)
const OpsDevolucionesIndexRoute = OpsDevolucionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsDevolucionesRoute,
} as any)
const OpsCotizacionesIndexRoute = OpsCotizacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsCotizacionesRoute,
} as any)
const OpsVentasNuevaRoute = OpsVentasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => OpsVentasRoute,
} as any)
const OpsVentasIdRoute = OpsVentasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsVentasRoute,
} as any)
const OpsRecibosNuevaRoute = OpsRecibosNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => OpsRecibosRoute,
} as any)
const OpsRecibosIdRoute = OpsRecibosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsRecibosRoute,
} as any)
const OpsOrdenesTrabajoIdRoute = OpsOrdenesTrabajoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsOrdenesTrabajoRoute,
} as any)
const OpsGarantiasNuevaRoute = OpsGarantiasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => OpsGarantiasRoute,
} as any)
const OpsGarantiasIdRoute = OpsGarantiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsGarantiasRoute,
} as any)
const OpsDevolucionesNuevaRoute = OpsDevolucionesNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => OpsDevolucionesRoute,
} as any)
const OpsDevolucionesIdRoute = OpsDevolucionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsDevolucionesRoute,
} as any)
const OpsCotizacionesNuevaRoute = OpsCotizacionesNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => OpsCotizacionesRoute,
} as any)
const OpsCotizacionesIdRoute = OpsCotizacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsCotizacionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/analisis-abc': typeof AdminAnalisisAbcRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cierres': typeof AdminCierresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/conteo-ciclico': typeof AdminConteoCiclicoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reorden': typeof AdminReordenRoute
  '/admin/top-10': typeof AdminTop10Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ops/compras': typeof OpsComprasRoute
  '/ops/cotizaciones': typeof OpsCotizacionesRouteWithChildren
  '/ops/devoluciones': typeof OpsDevolucionesRouteWithChildren
  '/ops/ensambles': typeof OpsEnsamblesRoute
  '/ops/garantias': typeof OpsGarantiasRouteWithChildren
  '/ops/herramientas': typeof OpsHerramientasRoute
  '/ops/inventario': typeof OpsInventarioRoute
  '/ops/ordenes-trabajo': typeof OpsOrdenesTrabajoRouteWithChildren
  '/ops/productos': typeof OpsProductosRoute
  '/ops/recibos': typeof OpsRecibosRouteWithChildren
  '/ops/traspasos': typeof OpsTraspasosRoute
  '/ops/ventas': typeof OpsVentasRouteWithChildren
  '/picking/$id': typeof PickingIdRoute
  '/ops/cotizaciones/$id': typeof OpsCotizacionesIdRoute
  '/ops/cotizaciones/nueva': typeof OpsCotizacionesNuevaRoute
  '/ops/devoluciones/$id': typeof OpsDevolucionesIdRoute
  '/ops/devoluciones/nueva': typeof OpsDevolucionesNuevaRoute
  '/ops/garantias/$id': typeof OpsGarantiasIdRoute
  '/ops/garantias/nueva': typeof OpsGarantiasNuevaRoute
  '/ops/ordenes-trabajo/$id': typeof OpsOrdenesTrabajoIdRoute
  '/ops/recibos/$id': typeof OpsRecibosIdRoute
  '/ops/recibos/nueva': typeof OpsRecibosNuevaRoute
  '/ops/ventas/$id': typeof OpsVentasIdRoute
  '/ops/ventas/nueva': typeof OpsVentasNuevaRoute
  '/ops/cotizaciones/': typeof OpsCotizacionesIndexRoute
  '/ops/devoluciones/': typeof OpsDevolucionesIndexRoute
  '/ops/garantias/': typeof OpsGarantiasIndexRoute
  '/ops/ordenes-trabajo/': typeof OpsOrdenesTrabajoIndexRoute
  '/ops/recibos/': typeof OpsRecibosIndexRoute
  '/ops/ventas/': typeof OpsVentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/analisis-abc': typeof AdminAnalisisAbcRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cierres': typeof AdminCierresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/conteo-ciclico': typeof AdminConteoCiclicoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reorden': typeof AdminReordenRoute
  '/admin/top-10': typeof AdminTop10Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ops/compras': typeof OpsComprasRoute
  '/ops/ensambles': typeof OpsEnsamblesRoute
  '/ops/herramientas': typeof OpsHerramientasRoute
  '/ops/inventario': typeof OpsInventarioRoute
  '/ops/productos': typeof OpsProductosRoute
  '/ops/traspasos': typeof OpsTraspasosRoute
  '/picking/$id': typeof PickingIdRoute
  '/ops/cotizaciones/$id': typeof OpsCotizacionesIdRoute
  '/ops/cotizaciones/nueva': typeof OpsCotizacionesNuevaRoute
  '/ops/devoluciones/$id': typeof OpsDevolucionesIdRoute
  '/ops/devoluciones/nueva': typeof OpsDevolucionesNuevaRoute
  '/ops/garantias/$id': typeof OpsGarantiasIdRoute
  '/ops/garantias/nueva': typeof OpsGarantiasNuevaRoute
  '/ops/ordenes-trabajo/$id': typeof OpsOrdenesTrabajoIdRoute
  '/ops/recibos/$id': typeof OpsRecibosIdRoute
  '/ops/recibos/nueva': typeof OpsRecibosNuevaRoute
  '/ops/ventas/$id': typeof OpsVentasIdRoute
  '/ops/ventas/nueva': typeof OpsVentasNuevaRoute
  '/ops/cotizaciones': typeof OpsCotizacionesIndexRoute
  '/ops/devoluciones': typeof OpsDevolucionesIndexRoute
  '/ops/garantias': typeof OpsGarantiasIndexRoute
  '/ops/ordenes-trabajo': typeof OpsOrdenesTrabajoIndexRoute
  '/ops/recibos': typeof OpsRecibosIndexRoute
  '/ops/ventas': typeof OpsVentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/analisis-abc': typeof AdminAnalisisAbcRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cierres': typeof AdminCierresRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/conteo-ciclico': typeof AdminConteoCiclicoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reorden': typeof AdminReordenRoute
  '/admin/top-10': typeof AdminTop10Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ops/compras': typeof OpsComprasRoute
  '/ops/cotizaciones': typeof OpsCotizacionesRouteWithChildren
  '/ops/devoluciones': typeof OpsDevolucionesRouteWithChildren
  '/ops/ensambles': typeof OpsEnsamblesRoute
  '/ops/garantias': typeof OpsGarantiasRouteWithChildren
  '/ops/herramientas': typeof OpsHerramientasRoute
  '/ops/inventario': typeof OpsInventarioRoute
  '/ops/ordenes-trabajo': typeof OpsOrdenesTrabajoRouteWithChildren
  '/ops/productos': typeof OpsProductosRoute
  '/ops/recibos': typeof OpsRecibosRouteWithChildren
  '/ops/traspasos': typeof OpsTraspasosRoute
  '/ops/ventas': typeof OpsVentasRouteWithChildren
  '/picking/$id': typeof PickingIdRoute
  '/ops/cotizaciones/$id': typeof OpsCotizacionesIdRoute
  '/ops/cotizaciones/nueva': typeof OpsCotizacionesNuevaRoute
  '/ops/devoluciones/$id': typeof OpsDevolucionesIdRoute
  '/ops/devoluciones/nueva': typeof OpsDevolucionesNuevaRoute
  '/ops/garantias/$id': typeof OpsGarantiasIdRoute
  '/ops/garantias/nueva': typeof OpsGarantiasNuevaRoute
  '/ops/ordenes-trabajo/$id': typeof OpsOrdenesTrabajoIdRoute
  '/ops/recibos/$id': typeof OpsRecibosIdRoute
  '/ops/recibos/nueva': typeof OpsRecibosNuevaRoute
  '/ops/ventas/$id': typeof OpsVentasIdRoute
  '/ops/ventas/nueva': typeof OpsVentasNuevaRoute
  '/ops/cotizaciones/': typeof OpsCotizacionesIndexRoute
  '/ops/devoluciones/': typeof OpsDevolucionesIndexRoute
  '/ops/garantias/': typeof OpsGarantiasIndexRoute
  '/ops/ordenes-trabajo/': typeof OpsOrdenesTrabajoIndexRoute
  '/ops/recibos/': typeof OpsRecibosIndexRoute
  '/ops/ventas/': typeof OpsVentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/ops'
    | '/admin/alertas'
    | '/admin/analisis-abc'
    | '/admin/auditoria'
    | '/admin/cierres'
    | '/admin/configuracion'
    | '/admin/conteo-ciclico'
    | '/admin/dashboard'
    | '/admin/reorden'
    | '/admin/top-10'
    | '/admin/usuarios'
    | '/ops/compras'
    | '/ops/cotizaciones'
    | '/ops/devoluciones'
    | '/ops/ensambles'
    | '/ops/garantias'
    | '/ops/herramientas'
    | '/ops/inventario'
    | '/ops/ordenes-trabajo'
    | '/ops/productos'
    | '/ops/recibos'
    | '/ops/traspasos'
    | '/ops/ventas'
    | '/picking/$id'
    | '/ops/cotizaciones/$id'
    | '/ops/cotizaciones/nueva'
    | '/ops/devoluciones/$id'
    | '/ops/devoluciones/nueva'
    | '/ops/garantias/$id'
    | '/ops/garantias/nueva'
    | '/ops/ordenes-trabajo/$id'
    | '/ops/recibos/$id'
    | '/ops/recibos/nueva'
    | '/ops/ventas/$id'
    | '/ops/ventas/nueva'
    | '/ops/cotizaciones/'
    | '/ops/devoluciones/'
    | '/ops/garantias/'
    | '/ops/ordenes-trabajo/'
    | '/ops/recibos/'
    | '/ops/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/ops'
    | '/admin/alertas'
    | '/admin/analisis-abc'
    | '/admin/auditoria'
    | '/admin/cierres'
    | '/admin/configuracion'
    | '/admin/conteo-ciclico'
    | '/admin/dashboard'
    | '/admin/reorden'
    | '/admin/top-10'
    | '/admin/usuarios'
    | '/ops/compras'
    | '/ops/ensambles'
    | '/ops/herramientas'
    | '/ops/inventario'
    | '/ops/productos'
    | '/ops/traspasos'
    | '/picking/$id'
    | '/ops/cotizaciones/$id'
    | '/ops/cotizaciones/nueva'
    | '/ops/devoluciones/$id'
    | '/ops/devoluciones/nueva'
    | '/ops/garantias/$id'
    | '/ops/garantias/nueva'
    | '/ops/ordenes-trabajo/$id'
    | '/ops/recibos/$id'
    | '/ops/recibos/nueva'
    | '/ops/ventas/$id'
    | '/ops/ventas/nueva'
    | '/ops/cotizaciones'
    | '/ops/devoluciones'
    | '/ops/garantias'
    | '/ops/ordenes-trabajo'
    | '/ops/recibos'
    | '/ops/ventas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/ops'
    | '/admin/alertas'
    | '/admin/analisis-abc'
    | '/admin/auditoria'
    | '/admin/cierres'
    | '/admin/configuracion'
    | '/admin/conteo-ciclico'
    | '/admin/dashboard'
    | '/admin/reorden'
    | '/admin/top-10'
    | '/admin/usuarios'
    | '/ops/compras'
    | '/ops/cotizaciones'
    | '/ops/devoluciones'
    | '/ops/ensambles'
    | '/ops/garantias'
    | '/ops/herramientas'
    | '/ops/inventario'
    | '/ops/ordenes-trabajo'
    | '/ops/productos'
    | '/ops/recibos'
    | '/ops/traspasos'
    | '/ops/ventas'
    | '/picking/$id'
    | '/ops/cotizaciones/$id'
    | '/ops/cotizaciones/nueva'
    | '/ops/devoluciones/$id'
    | '/ops/devoluciones/nueva'
    | '/ops/garantias/$id'
    | '/ops/garantias/nueva'
    | '/ops/ordenes-trabajo/$id'
    | '/ops/recibos/$id'
    | '/ops/recibos/nueva'
    | '/ops/ventas/$id'
    | '/ops/ventas/nueva'
    | '/ops/cotizaciones/'
    | '/ops/devoluciones/'
    | '/ops/garantias/'
    | '/ops/ordenes-trabajo/'
    | '/ops/recibos/'
    | '/ops/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PickingIdRoute: typeof PickingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking/$id': {
      id: '/picking/$id'
      path: '/picking/$id'
      fullPath: '/picking/$id'
      preLoaderRoute: typeof PickingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/ventas': {
      id: '/ops/ventas'
      path: '/ventas'
      fullPath: '/ops/ventas'
      preLoaderRoute: typeof OpsVentasRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/traspasos': {
      id: '/ops/traspasos'
      path: '/traspasos'
      fullPath: '/ops/traspasos'
      preLoaderRoute: typeof OpsTraspasosRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/recibos': {
      id: '/ops/recibos'
      path: '/recibos'
      fullPath: '/ops/recibos'
      preLoaderRoute: typeof OpsRecibosRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/productos': {
      id: '/ops/productos'
      path: '/productos'
      fullPath: '/ops/productos'
      preLoaderRoute: typeof OpsProductosRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/ordenes-trabajo': {
      id: '/ops/ordenes-trabajo'
      path: '/ordenes-trabajo'
      fullPath: '/ops/ordenes-trabajo'
      preLoaderRoute: typeof OpsOrdenesTrabajoRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventario': {
      id: '/ops/inventario'
      path: '/inventario'
      fullPath: '/ops/inventario'
      preLoaderRoute: typeof OpsInventarioRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/herramientas': {
      id: '/ops/herramientas'
      path: '/herramientas'
      fullPath: '/ops/herramientas'
      preLoaderRoute: typeof OpsHerramientasRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/garantias': {
      id: '/ops/garantias'
      path: '/garantias'
      fullPath: '/ops/garantias'
      preLoaderRoute: typeof OpsGarantiasRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/ensambles': {
      id: '/ops/ensambles'
      path: '/ensambles'
      fullPath: '/ops/ensambles'
      preLoaderRoute: typeof OpsEnsamblesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/devoluciones': {
      id: '/ops/devoluciones'
      path: '/devoluciones'
      fullPath: '/ops/devoluciones'
      preLoaderRoute: typeof OpsDevolucionesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/cotizaciones': {
      id: '/ops/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/ops/cotizaciones'
      preLoaderRoute: typeof OpsCotizacionesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/compras': {
      id: '/ops/compras'
      path: '/compras'
      fullPath: '/ops/compras'
      preLoaderRoute: typeof OpsComprasRouteImport
      parentRoute: typeof OpsRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/top-10': {
      id: '/admin/top-10'
      path: '/top-10'
      fullPath: '/admin/top-10'
      preLoaderRoute: typeof AdminTop10RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reorden': {
      id: '/admin/reorden'
      path: '/reorden'
      fullPath: '/admin/reorden'
      preLoaderRoute: typeof AdminReordenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteo-ciclico': {
      id: '/admin/conteo-ciclico'
      path: '/conteo-ciclico'
      fullPath: '/admin/conteo-ciclico'
      preLoaderRoute: typeof AdminConteoCiclicoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cierres': {
      id: '/admin/cierres'
      path: '/cierres'
      fullPath: '/admin/cierres'
      preLoaderRoute: typeof AdminCierresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analisis-abc': {
      id: '/admin/analisis-abc'
      path: '/analisis-abc'
      fullPath: '/admin/analisis-abc'
      preLoaderRoute: typeof AdminAnalisisAbcRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ops/ventas/': {
      id: '/ops/ventas/'
      path: '/'
      fullPath: '/ops/ventas/'
      preLoaderRoute: typeof OpsVentasIndexRouteImport
      parentRoute: typeof OpsVentasRoute
    }
    '/ops/recibos/': {
      id: '/ops/recibos/'
      path: '/'
      fullPath: '/ops/recibos/'
      preLoaderRoute: typeof OpsRecibosIndexRouteImport
      parentRoute: typeof OpsRecibosRoute
    }
    '/ops/ordenes-trabajo/': {
      id: '/ops/ordenes-trabajo/'
      path: '/'
      fullPath: '/ops/ordenes-trabajo/'
      preLoaderRoute: typeof OpsOrdenesTrabajoIndexRouteImport
      parentRoute: typeof OpsOrdenesTrabajoRoute
    }
    '/ops/garantias/': {
      id: '/ops/garantias/'
      path: '/'
      fullPath: '/ops/garantias/'
      preLoaderRoute: typeof OpsGarantiasIndexRouteImport
      parentRoute: typeof OpsGarantiasRoute
    }
    '/ops/devoluciones/': {
      id: '/ops/devoluciones/'
      path: '/'
      fullPath: '/ops/devoluciones/'
      preLoaderRoute: typeof OpsDevolucionesIndexRouteImport
      parentRoute: typeof OpsDevolucionesRoute
    }
    '/ops/cotizaciones/': {
      id: '/ops/cotizaciones/'
      path: '/'
      fullPath: '/ops/cotizaciones/'
      preLoaderRoute: typeof OpsCotizacionesIndexRouteImport
      parentRoute: typeof OpsCotizacionesRoute
    }
    '/ops/ventas/nueva': {
      id: '/ops/ventas/nueva'
      path: '/nueva'
      fullPath: '/ops/ventas/nueva'
      preLoaderRoute: typeof OpsVentasNuevaRouteImport
      parentRoute: typeof OpsVentasRoute
    }
    '/ops/ventas/$id': {
      id: '/ops/ventas/$id'
      path: '/$id'
      fullPath: '/ops/ventas/$id'
      preLoaderRoute: typeof OpsVentasIdRouteImport
      parentRoute: typeof OpsVentasRoute
    }
    '/ops/recibos/nueva': {
      id: '/ops/recibos/nueva'
      path: '/nueva'
      fullPath: '/ops/recibos/nueva'
      preLoaderRoute: typeof OpsRecibosNuevaRouteImport
      parentRoute: typeof OpsRecibosRoute
    }
    '/ops/recibos/$id': {
      id: '/ops/recibos/$id'
      path: '/$id'
      fullPath: '/ops/recibos/$id'
      preLoaderRoute: typeof OpsRecibosIdRouteImport
      parentRoute: typeof OpsRecibosRoute
    }
    '/ops/ordenes-trabajo/$id': {
      id: '/ops/ordenes-trabajo/$id'
      path: '/$id'
      fullPath: '/ops/ordenes-trabajo/$id'
      preLoaderRoute: typeof OpsOrdenesTrabajoIdRouteImport
      parentRoute: typeof OpsOrdenesTrabajoRoute
    }
    '/ops/garantias/nueva': {
      id: '/ops/garantias/nueva'
      path: '/nueva'
      fullPath: '/ops/garantias/nueva'
      preLoaderRoute: typeof OpsGarantiasNuevaRouteImport
      parentRoute: typeof OpsGarantiasRoute
    }
    '/ops/garantias/$id': {
      id: '/ops/garantias/$id'
      path: '/$id'
      fullPath: '/ops/garantias/$id'
      preLoaderRoute: typeof OpsGarantiasIdRouteImport
      parentRoute: typeof OpsGarantiasRoute
    }
    '/ops/devoluciones/nueva': {
      id: '/ops/devoluciones/nueva'
      path: '/nueva'
      fullPath: '/ops/devoluciones/nueva'
      preLoaderRoute: typeof OpsDevolucionesNuevaRouteImport
      parentRoute: typeof OpsDevolucionesRoute
    }
    '/ops/devoluciones/$id': {
      id: '/ops/devoluciones/$id'
      path: '/$id'
      fullPath: '/ops/devoluciones/$id'
      preLoaderRoute: typeof OpsDevolucionesIdRouteImport
      parentRoute: typeof OpsDevolucionesRoute
    }
    '/ops/cotizaciones/nueva': {
      id: '/ops/cotizaciones/nueva'
      path: '/nueva'
      fullPath: '/ops/cotizaciones/nueva'
      preLoaderRoute: typeof OpsCotizacionesNuevaRouteImport
      parentRoute: typeof OpsCotizacionesRoute
    }
    '/ops/cotizaciones/$id': {
      id: '/ops/cotizaciones/$id'
      path: '/$id'
      fullPath: '/ops/cotizaciones/$id'
      preLoaderRoute: typeof OpsCotizacionesIdRouteImport
      parentRoute: typeof OpsCotizacionesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminAnalisisAbcRoute: typeof AdminAnalisisAbcRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCierresRoute: typeof AdminCierresRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminConteoCiclicoRoute: typeof AdminConteoCiclicoRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReordenRoute: typeof AdminReordenRoute
  AdminTop10Route: typeof AdminTop10Route
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminAnalisisAbcRoute: AdminAnalisisAbcRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCierresRoute: AdminCierresRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminConteoCiclicoRoute: AdminConteoCiclicoRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReordenRoute: AdminReordenRoute,
  AdminTop10Route: AdminTop10Route,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OpsCotizacionesRouteChildren {
  OpsCotizacionesIdRoute: typeof OpsCotizacionesIdRoute
  OpsCotizacionesNuevaRoute: typeof OpsCotizacionesNuevaRoute
  OpsCotizacionesIndexRoute: typeof OpsCotizacionesIndexRoute
}

const OpsCotizacionesRouteChildren: OpsCotizacionesRouteChildren = {
  OpsCotizacionesIdRoute: OpsCotizacionesIdRoute,
  OpsCotizacionesNuevaRoute: OpsCotizacionesNuevaRoute,
  OpsCotizacionesIndexRoute: OpsCotizacionesIndexRoute,
}

const OpsCotizacionesRouteWithChildren = OpsCotizacionesRoute._addFileChildren(
  OpsCotizacionesRouteChildren,
)

interface OpsDevolucionesRouteChildren {
  OpsDevolucionesIdRoute: typeof OpsDevolucionesIdRoute
  OpsDevolucionesNuevaRoute: typeof OpsDevolucionesNuevaRoute
  OpsDevolucionesIndexRoute: typeof OpsDevolucionesIndexRoute
}

const OpsDevolucionesRouteChildren: OpsDevolucionesRouteChildren = {
  OpsDevolucionesIdRoute: OpsDevolucionesIdRoute,
  OpsDevolucionesNuevaRoute: OpsDevolucionesNuevaRoute,
  OpsDevolucionesIndexRoute: OpsDevolucionesIndexRoute,
}

const OpsDevolucionesRouteWithChildren = OpsDevolucionesRoute._addFileChildren(
  OpsDevolucionesRouteChildren,
)

interface OpsGarantiasRouteChildren {
  OpsGarantiasIdRoute: typeof OpsGarantiasIdRoute
  OpsGarantiasNuevaRoute: typeof OpsGarantiasNuevaRoute
  OpsGarantiasIndexRoute: typeof OpsGarantiasIndexRoute
}

const OpsGarantiasRouteChildren: OpsGarantiasRouteChildren = {
  OpsGarantiasIdRoute: OpsGarantiasIdRoute,
  OpsGarantiasNuevaRoute: OpsGarantiasNuevaRoute,
  OpsGarantiasIndexRoute: OpsGarantiasIndexRoute,
}

const OpsGarantiasRouteWithChildren = OpsGarantiasRoute._addFileChildren(
  OpsGarantiasRouteChildren,
)

interface OpsOrdenesTrabajoRouteChildren {
  OpsOrdenesTrabajoIdRoute: typeof OpsOrdenesTrabajoIdRoute
  OpsOrdenesTrabajoIndexRoute: typeof OpsOrdenesTrabajoIndexRoute
}

const OpsOrdenesTrabajoRouteChildren: OpsOrdenesTrabajoRouteChildren = {
  OpsOrdenesTrabajoIdRoute: OpsOrdenesTrabajoIdRoute,
  OpsOrdenesTrabajoIndexRoute: OpsOrdenesTrabajoIndexRoute,
}

const OpsOrdenesTrabajoRouteWithChildren =
  OpsOrdenesTrabajoRoute._addFileChildren(OpsOrdenesTrabajoRouteChildren)

interface OpsRecibosRouteChildren {
  OpsRecibosIdRoute: typeof OpsRecibosIdRoute
  OpsRecibosNuevaRoute: typeof OpsRecibosNuevaRoute
  OpsRecibosIndexRoute: typeof OpsRecibosIndexRoute
}

const OpsRecibosRouteChildren: OpsRecibosRouteChildren = {
  OpsRecibosIdRoute: OpsRecibosIdRoute,
  OpsRecibosNuevaRoute: OpsRecibosNuevaRoute,
  OpsRecibosIndexRoute: OpsRecibosIndexRoute,
}

const OpsRecibosRouteWithChildren = OpsRecibosRoute._addFileChildren(
  OpsRecibosRouteChildren,
)

interface OpsVentasRouteChildren {
  OpsVentasIdRoute: typeof OpsVentasIdRoute
  OpsVentasNuevaRoute: typeof OpsVentasNuevaRoute
  OpsVentasIndexRoute: typeof OpsVentasIndexRoute
}

const OpsVentasRouteChildren: OpsVentasRouteChildren = {
  OpsVentasIdRoute: OpsVentasIdRoute,
  OpsVentasNuevaRoute: OpsVentasNuevaRoute,
  OpsVentasIndexRoute: OpsVentasIndexRoute,
}

const OpsVentasRouteWithChildren = OpsVentasRoute._addFileChildren(
  OpsVentasRouteChildren,
)

interface OpsRouteChildren {
  OpsComprasRoute: typeof OpsComprasRoute
  OpsCotizacionesRoute: typeof OpsCotizacionesRouteWithChildren
  OpsDevolucionesRoute: typeof OpsDevolucionesRouteWithChildren
  OpsEnsamblesRoute: typeof OpsEnsamblesRoute
  OpsGarantiasRoute: typeof OpsGarantiasRouteWithChildren
  OpsHerramientasRoute: typeof OpsHerramientasRoute
  OpsInventarioRoute: typeof OpsInventarioRoute
  OpsOrdenesTrabajoRoute: typeof OpsOrdenesTrabajoRouteWithChildren
  OpsProductosRoute: typeof OpsProductosRoute
  OpsRecibosRoute: typeof OpsRecibosRouteWithChildren
  OpsTraspasosRoute: typeof OpsTraspasosRoute
  OpsVentasRoute: typeof OpsVentasRouteWithChildren
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsComprasRoute: OpsComprasRoute,
  OpsCotizacionesRoute: OpsCotizacionesRouteWithChildren,
  OpsDevolucionesRoute: OpsDevolucionesRouteWithChildren,
  OpsEnsamblesRoute: OpsEnsamblesRoute,
  OpsGarantiasRoute: OpsGarantiasRouteWithChildren,
  OpsHerramientasRoute: OpsHerramientasRoute,
  OpsInventarioRoute: OpsInventarioRoute,
  OpsOrdenesTrabajoRoute: OpsOrdenesTrabajoRouteWithChildren,
  OpsProductosRoute: OpsProductosRoute,
  OpsRecibosRoute: OpsRecibosRouteWithChildren,
  OpsTraspasosRoute: OpsTraspasosRoute,
  OpsVentasRoute: OpsVentasRouteWithChildren,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PickingIdRoute: PickingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
